swagger: '2.0'
info:
  title: RPi Environment Sensors Reader
  description: |
    Sensor reader for the Raspberry Pi.
    Can turn a lamp on or off
  version: "0.0.2"
host: localhost:8765
schemes:
  - http
basePath: /v1
produces:
  - application/json
consumes:
  - application/json
paths:
  /sensors/ambient-light:
    get:
      description: |
        Read data from photo cell sensor (aka light sensor, photo-resistor).
      operationId: readAmbientLight
      tags:
        - Sensors
      responses:
        200:
          description: "Read successful"
          schema:
            $ref: "#/definitions/ambient-light"

  /sensors/relay:
    put:
      description: |
        Turn the relay on or off
      operationId: setRelayStatus
      parameters:
        - name: onOff
          schema:
            $ref: "#/definitions/relay-status"
          in: body
      tags:
        - Relay
      responses:
        200:
          description: Start or stop the pump
          schema:
            $ref: "#/definitions/relay-status"
    get:
      description: Get the current relay status
      operationId: getRelayStatus
      tags:
        - Relay
      responses:
        200:
          description: Got status OK
          schema:
            $ref: "#/definitions/relay-status"

definitions:

  relay-status:
    type: object
    description: Relay status, on or off
    properties:
      status:
        type: boolean
        description: On if true, Off if false

  ambient-light:
    type: object
    description: Ambient light in %
    properties:
      light:
        type: number
        minimum: 0.0
        maximum: 100.0
        format: float

