openapi: 3.0.1
info:
  title: RPi Environment Sensors Reader
  termsOfService: 'urn://Use-and-Reuse-at-will'
  description: |
    Simple example. Automatically turns a light on or off based on the ambient light.
    From this [Repo](https://github.com/OlivierLD/raspberry-coffee/tree/master/polo-shirt).
  version: "1.0.0"
  contact:
    email: "olivier@lediouris.net"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: 'http://localhost:8765'
paths:
  /sensors/ambient-light:
    get:
      description: |
        Read data from photo cell sensor (aka light sensor, photo-resistor).
      operationId: readAmbientLight
      tags:
        - Sensors
      responses:
        '200':
          description: "Read successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ambient-light"

  /sensors/relay:
    put:
      description: |
        Turn the relay on or off
      operationId: setRelayStatus
      requestBody:
        $ref: "#/components/requestBodies/relay-status"
      tags:
        - Relay
      responses:
        '200':
          description: Start or stop the pump
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/relay-status"
    get:
      description: Get the current relay status
      operationId: getRelayStatus
      tags:
        - Relay
      responses:
        '200':
          description: Got status OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/relay-status"

components:
  schemas:
    relay-status:
      type: object
      description: Relay status, on or off
      properties:
        status:
          type: boolean
          description: On if true, Off if false

    ambient-light:
      type: object
      description: Ambient light in %
      properties:
        light:
          type: number
          minimum: 0.0
          maximum: 100.0
          format: float
  requestBodies:
    relay-status:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/relay-status'
      description: The relay status to set
