schema_version: 20180708
name: ambientlight
version: 0.0.6
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.98
run_image: fnproject/fn-java-fdk:jre11-1.0.98
cmd: rpi.sensors.LightSensor::handleRequest
triggers:
- name: ambientlight
  type: http
  source: /ambientlight
